spring:
  application:
    name: company-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6