server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PUT,DELETE
        - name: CircuitBreaker
          args:
            name: default-circuit-breaker
            fallback-uri: forward:/fallback

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway