server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/job_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect